### ISSUE TITLE
progetto incompleto

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/FioreNicoloAntonio#1]
Il tuo progetto non può essere valutato in quanto manca la relazione PDF ed il link al video dimostrativo

**Comment by NicooFiore** [comment]
Buongiorno professore ho provveduto a caricare il materiale mancante, attendo suoi aggiornamenti per ricevere conferma e poter effettuare l'iscrizione alla prova finale.
Grazie in anticipo dell'attenzione
